# Generated by Django 4.0.6 on 2022-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
